version: "3.8"

services:
  frontend:
    container_name: marga-accounting-system-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
